name = "work-tracker"                    # Your project name
type = "javascript"                      # JS/React project
account_id = "cfat_aSzv53TCMHP2S8opD8Upkx2FU5PmX069OSWpAFCZ34c3cce3"
workers_dev = true
compatibility_date = "2026-03-26"       # Set today or current date

[build]
command = "npm run build"                # Build command
directory = "dist"                       # Output folder for Pages
